-- Enum types for Cached SaaS

CREATE TYPE plan_type AS ENUM ('FREE', 'PRO');
CREATE TYPE week_start_day AS ENUM ('SUNDAY', 'MONDAY');
CREATE TYPE content_format AS ENUM ('VIDEO', 'AUDIO', 'LONG_READ', 'SHORT_READ', 'CODE_REPO');
CREATE TYPE source_platform AS ENUM ('YOUTUBE', 'TWITTER', 'LINKEDIN', 'SPOTIFY', 'PODCAST', 'GITHUB', 'NEWSLETTER', 'ARTICLE', 'OTHER');
CREATE TYPE content_status AS ENUM ('QUEUED', 'SCHEDULED', 'CONSUMED', 'SKIPPED', 'ARCHIVED');
CREATE TYPE block_status AS ENUM ('UPCOMING', 'COMPLETED', 'SKIPPED');
CREATE TYPE day_of_week AS ENUM ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY');
CREATE TYPE subscription_status AS ENUM ('ACTIVE', 'PAST_DUE', 'CANCELED', 'TRIALING');
